'use client';

import { useState, useEffect } from 'react';
import { 
  collection, 
  doc, 
  addDoc, 
  updateDoc, 
  onSnapshot,
  serverTimestamp
} from 'firebase/firestore';
import { db } from '@/lib/firebase/client';
import { useAuth } from '@/contexts/AuthContext';
import type { CarePlan, CarePlanCard } from '@/lib/firebase/types';

export function useCarePlan(patientId: string) {
  const { organization, staff } = useAuth();
  const [carePlan, setCarePlan] = useState<CarePlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!organization?.id || !patientId) {
      setLoading(false);
      return;
    }

    setLoading(true);
    
    // Scoped collection: organizations/{org_id}/patients/{patientId}/care_plans
    const carePlansRef = collection(db, 'organizations', organization.id, 'patients', patientId, 'care_plans');

    // Fetch all care plans and sort in-memory to prevent index errors
    const unsubscribe = onSnapshot(carePlansRef, (snapshot) => {
      const plans = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as CarePlan[];

      // Filter non-archived, and sort by updated_at descending
      const activeOrDraft = plans
        .filter(p => p.status === 'draft' || p.status === 'active')
        .sort((a, b) => {
          const aTime = (a.updated_at as any)?.seconds ? (a.updated_at as any).seconds * 1000 : new Date(a.updated_at || 0).getTime();
          const bTime = (b.updated_at as any)?.seconds ? (b.updated_at as any).seconds * 1000 : new Date(b.updated_at || 0).getTime();
          return bTime - aTime;
        });

      setCarePlan(activeOrDraft[0] || null);
      setLoading(false);
    }, (err) => {
      console.error('Error fetching care plans:', err);
      setError('Failed to load care plan records.');
      setLoading(false);
    });

    return () => unsubscribe();
  }, [organization?.id, patientId]);

  const generateCarePlanAI = async (
    patientProfile: any, 
    confirmedDiagnosis: string, 
    baselines: string[], 
    notes: string
  ): Promise<CarePlanCard[]> => {
    const response = await fetch('/api/clinical/generate-care-plan', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        patient: patientProfile,
        confirmedDiagnosis,
        baselines,
        notes
      })
    });

    if (!response.ok) {
      const errData = await response.json();
      throw new Error(errData.details || 'Failed to generate care plan via AI');
    }

    const data = await response.json();
    return data.cards as CarePlanCard[];
  };

  const saveDraft = async (cards: CarePlanCard[]) => {
    if (!organization?.id || !patientId) throw new Error('Not authenticated');

    const disclaimerText = 'Generated by AI Assistant. Must be reviewed, edited, and signed by a licensed nurse prior to implementation.';

    if (carePlan && carePlan.id) {
      if (carePlan.status !== 'draft') {
        throw new Error('Cannot edit an active signed clinical chart. Discontinue or archive first.');
      }
      // Update existing draft
      const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlan.id);
      return await updateDoc(planRef, {
        cards,
        updated_at: serverTimestamp()
      });
    } else {
      // Create new draft
      const carePlansRef = collection(db, 'organizations', organization.id, 'patients', patientId, 'care_plans');
      return await addDoc(carePlansRef, {
        org_id: organization.id,
        patient_id: patientId,
        status: 'draft',
        cards,
        disclaimer: disclaimerText,
        created_at: serverTimestamp(),
        updated_at: serverTimestamp()
      });
    }
  };

  const approveAndSign = async (carePlanId: string, cards: CarePlanCard[], signature: string) => {
    if (!organization?.id || !patientId || !staff) throw new Error('Not authenticated');

    const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlanId);
    return await updateDoc(planRef, {
      cards,
      status: 'active',
      signed_by: staff.id,
      signed_by_name: signature,
      signed_at: new Date().toISOString(),
      updated_at: serverTimestamp()
    });
  };

  const archivePlan = async (carePlanId: string) => {
    if (!organization?.id || !patientId) throw new Error('Not authenticated');

    const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlanId);
    return await updateDoc(planRef, {
      status: 'archived',
      updated_at: serverTimestamp()
    });
  };

  return {
    carePlan,
    loading,
    error,
    generateCarePlanAI,
    saveDraft,
    approveAndSign,
    archivePlan
  };
}
