'use client';

import { useState, useEffect } from 'react';
import { 
  collection, 
  doc, 
  addDoc, 
  updateDoc, 
  onSnapshot,
  serverTimestamp
} from 'firebase/firestore';
import { db } from '@/lib/firebase/client';
import { useAuth } from '@/contexts/AuthContext';
import type { CarePlan, CarePlanCard } from '@/lib/firebase/types';

export function useCarePlan(patientId: string) {
  const { organization, staff } = useAuth();
  const [carePlan, setCarePlan] = useState<CarePlan | null>(null);
  const [history, setHistory] = useState<CarePlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!organization?.id || !patientId) {
      const timer = setTimeout(() => {
        setLoading(false);
      }, 0);
      return () => clearTimeout(timer);
    }

    const startTimer = setTimeout(() => {
      setLoading(true);
    }, 0);
    
    // Scoped collection: organizations/{org_id}/patients/{patientId}/care_plans
    const carePlansRef = collection(db, 'organizations', organization.id, 'patients', patientId, 'care_plans');

    // Fetch all care plans and sort in-memory to prevent index errors
    const unsubscribe = onSnapshot(carePlansRef, (snapshot) => {
      const plans = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as CarePlan[];

      // Filter active or draft plans, and sort by updated_at descending
      const activeOrDraft = plans
        .filter(p => p.status === 'draft' || p.status === 'active')
        .sort((a, b) => {
          const aTime = typeof a.updated_at === 'object' && a.updated_at && 'seconds' in a.updated_at
            ? (a.updated_at as { seconds: number }).seconds * 1000 
            : new Date(a.updated_at as string || 0).getTime();
          const bTime = typeof b.updated_at === 'object' && b.updated_at && 'seconds' in b.updated_at
            ? (b.updated_at as { seconds: number }).seconds * 1000 
            : new Date(b.updated_at as string || 0).getTime();
          return bTime - aTime;
        });

      // Filter historical/archived/superseded plans, sorted by signed_at or updated_at descending
      const historyPlans = plans
        .filter(p => p.status === 'archived' || p.status === 'superseded')
        .sort((a, b) => {
          const aTime = a.signed_at ? new Date(a.signed_at).getTime() : (
            typeof a.updated_at === 'object' && a.updated_at && 'seconds' in a.updated_at
              ? (a.updated_at as { seconds: number }).seconds * 1000
              : new Date(a.updated_at as string || 0).getTime()
          );
          const bTime = b.signed_at ? new Date(b.signed_at).getTime() : (
            typeof b.updated_at === 'object' && b.updated_at && 'seconds' in b.updated_at
              ? (b.updated_at as { seconds: number }).seconds * 1000
              : new Date(b.updated_at as string || 0).getTime()
          );
          return bTime - aTime;
        });

      setCarePlan(activeOrDraft[0] || null);
      setHistory(historyPlans);
      setLoading(false);
    }, (err) => {
      console.error('Error fetching care plans:', err);
      setError('Failed to load care plan records.');
      setLoading(false);
    });

    return () => {
      clearTimeout(startTimer);
      unsubscribe();
    };
  }, [organization?.id, patientId]);

  const generateCarePlanAI = async (
    patientProfile: unknown, 
    confirmedDiagnosis: string, 
    baselines: string[], 
    notes: string
  ): Promise<CarePlanCard[]> => {
    const response = await fetch('/api/clinical/generate-care-plan', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        patient: patientProfile,
        confirmedDiagnosis,
        baselines,
        notes
      })
    });

    if (!response.ok) {
      const errData = await response.json();
      throw new Error(errData.details || 'Failed to generate care plan via AI');
    }

    const data = await response.json();
    return data.cards as CarePlanCard[];
  };

  const saveDraft = async (cards: CarePlanCard[]) => {
    if (!organization?.id || !patientId) throw new Error('Not authenticated');

    const disclaimerText = 'Generated by AI Assistant. Must be reviewed, edited, and signed by a licensed nurse prior to implementation.';

    if (carePlan && carePlan.id) {
      if (carePlan.status !== 'draft') {
        throw new Error('Cannot edit an active signed clinical chart. Discontinue or archive first.');
      }
      // Update existing draft
      const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlan.id);
      return await updateDoc(planRef, {
        cards,
        updated_at: serverTimestamp()
      });
    } else {
      // Create new draft
      const carePlansRef = collection(db, 'organizations', organization.id, 'patients', patientId, 'care_plans');
      return await addDoc(carePlansRef, {
        org_id: organization.id,
        patient_id: patientId,
        status: 'draft',
        cards,
        disclaimer: disclaimerText,
        created_at: serverTimestamp(),
        updated_at: serverTimestamp()
      });
    }
  };

  const revisePlan = async (parentPlan: CarePlan) => {
    if (!organization?.id || !patientId) throw new Error('Not authenticated');

    const disclaimerText = 'Generated by AI Assistant. Must be reviewed, edited, and signed by a licensed nurse prior to implementation.';
    const carePlansRef = collection(db, 'organizations', organization.id, 'patients', patientId, 'care_plans');
    
    // Deep copy current cards to prevent reference leaks
    const cardsCopy = JSON.parse(JSON.stringify(parentPlan.cards)) as CarePlanCard[];
    const nextRevision = (parentPlan.revision || 1) + 1;

    return await addDoc(carePlansRef, {
      org_id: organization.id,
      patient_id: patientId,
      status: 'draft',
      cards: cardsCopy,
      disclaimer: disclaimerText,
      revision: nextRevision,
      parent_plan_id: parentPlan.id,
      created_at: serverTimestamp(),
      updated_at: serverTimestamp()
    });
  };

  const approveAndSign = async (carePlanId: string, cards: CarePlanCard[], signature: string, parentPlanId?: string) => {
    if (!organization?.id || !patientId || !staff) throw new Error('Not authenticated');

    const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlanId);
    
    // 1. Sign and activate the new plan
    await updateDoc(planRef, {
      cards,
      status: 'active',
      signed_by: staff.id,
      signed_by_name: signature,
      signed_at: new Date().toISOString(),
      updated_at: serverTimestamp()
    });

    // 2. If a parent plan or another active plan exists, supersede it to ensure exactly one active sheet
    const targetParentId = parentPlanId || (carePlan && carePlan.status === 'active' && carePlan.id !== carePlanId ? carePlan.id : null);
    if (targetParentId) {
      const parentRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', targetParentId);
      await updateDoc(parentRef, {
        status: 'superseded',
        superseded_at: new Date().toISOString(),
        superseded_by: staff.id,
        superseded_by_name: signature,
        updated_at: serverTimestamp()
      });
    }
  };

  const archivePlan = async (carePlanId: string) => {
    if (!organization?.id || !patientId) throw new Error('Not authenticated');

    const planRef = doc(db, 'organizations', organization.id, 'patients', patientId, 'care_plans', carePlanId);
    return await updateDoc(planRef, {
      status: 'archived',
      updated_at: serverTimestamp()
    });
  };

  return {
    carePlan,
    history,
    loading,
    error,
    generateCarePlanAI,
    saveDraft,
    approveAndSign,
    archivePlan,
    revisePlan
  };
}
